import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className="bg-white h-screen w-screen flex justify-center items-center">
      <body>{children}</body>
    </html>
  )
}
